"""Supported workflow integration shell subtypes observed from Jotform Builder."""
from __future__ import annotations

from typing import Literal

SUPPORTED_WORKFLOW_INTEGRATION_SUBTYPES = [
    "activecampaign",
    "airtable",
    "asana",
    "aweber",
    "box",
    "brevo",
    "campaign-monitor",
    "canvas-lms",
    "clickup",
    "constantContactV2",
    "dropbox",
    "egnyte",
    "freshdesk",
    "getresponse",
    "gohighlevel",
    "google-calendar",
    "google-drive",
    "google-sheetsV2",
    "hubspot",
    "jira",
    "jotform-boards",
    "linear",
    "mailchimp",
    "mailerlite",
    "mailsoftly",
    "microsoft-excel",
    "microsoft-sharepoint",
    "microsoft-teams",
    "monday",
    "onedrive",
    "outlook-calendar",
    "pipedrive",
    "quickbooks",
    "sendgrid",
    "slack",
    "smartsheet",
    "sms",
    "todoist",
    "whatsapp",
    "whatsapp-business",
    "zendesk",
    "zoom",
]

SupportedWorkflowIntegrationSubType = Literal[
    "activecampaign",
    "airtable",
    "asana",
    "aweber",
    "box",
    "brevo",
    "campaign-monitor",
    "canvas-lms",
    "clickup",
    "constantContactV2",
    "dropbox",
    "egnyte",
    "freshdesk",
    "getresponse",
    "gohighlevel",
    "google-calendar",
    "google-drive",
    "google-sheetsV2",
    "hubspot",
    "jira",
    "jotform-boards",
    "linear",
    "mailchimp",
    "mailerlite",
    "mailsoftly",
    "microsoft-excel",
    "microsoft-sharepoint",
    "microsoft-teams",
    "monday",
    "onedrive",
    "outlook-calendar",
    "pipedrive",
    "quickbooks",
    "sendgrid",
    "slack",
    "smartsheet",
    "sms",
    "todoist",
    "whatsapp",
    "whatsapp-business",
    "zendesk",
    "zoom",
]


def supported_integration_subtypes_text() -> str:
    return ", ".join(SUPPORTED_WORKFLOW_INTEGRATION_SUBTYPES)
